"""add conversation history and unique index on member ID and season on sequence table

Revision ID: 3f93a2490122
Revises: e1dfaad0d7dc
Create Date: 2023-11-26 15:18:18.452525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f93a2490122'
down_revision = 'e1dfaad0d7dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sequence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conversation_history', sa.Text(), nullable=True))
        batch_op.create_unique_constraint('member_id_season_unique_idx', ['member_id', 'season'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sequence', schema=None) as batch_op:
        batch_op.drop_constraint('member_id_season_unique_idx', type_='unique')
        batch_op.drop_column('conversation_history')

    # ### end Alembic commands ###
