"""actually adding message log table doh

Revision ID: 7f7a7270ff8f
Revises: f30b77816975
Create Date: 2023-11-25 17:06:11.743771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f7a7270ff8f'
down_revision = 'f30b77816975'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('message_sid', sa.String(length=255), nullable=False),
    sa.Column('message_body', sa.String(length=255), nullable=True),
    sa.Column('to_number', sa.String(length=255), nullable=False),
    sa.Column('from_number', sa.Text(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('created_ts', sa.Integer(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('last_modified_ts', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_sid')
    )
    with op.batch_alter_table('message_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_log_member_id'), ['member_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_log_member_id'))

    op.drop_table('message_log')
    # ### end Alembic commands ###
