"""add sequence table and member relation to message log

Revision ID: 991617a00a94
Revises: af98b178fd0b
Create Date: 2023-11-25 21:18:53.199746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '991617a00a94'
down_revision = 'af98b178fd0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sequence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=4), nullable=False),
    sa.Column('stage', sa.Enum('Initialized', 'Introduction_Sent', 'Participant_Confirmation', 'Wishlist_Request_Sent', 'Address_Request_Sent', 'Other_Question_Sent', 'Request_Received', 'Technical_Error', 'Unable_to_Process', name='sequencestageenum'), nullable=False),
    sa.Column('conversation_summary', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('created_ts', sa.Integer(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('last_modified_ts', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sequence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sequence_member_id'), ['member_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sequence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sequence_member_id'))

    op.drop_table('sequence')
    # ### end Alembic commands ###
