"""adding seasonal preference table

Revision ID: b4a6a6aa5bf6
Revises: 3f93a2490122
Create Date: 2023-11-26 15:47:25.672840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4a6a6aa5bf6'
down_revision = '3f93a2490122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seasonal_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=4), nullable=False),
    sa.Column('wishlist', sa.Text(), nullable=True),
    sa.Column('secret_santee_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('created_ts', sa.Integer(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('last_modified_ts', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['secret_santee_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'season', name='member_id_season_unique_idx_sp'),
    sa.UniqueConstraint('secret_santee_id', 'season', name='secret_santee_id_season_unique_idx_sp')
    )
    with op.batch_alter_table('seasonal_preference', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seasonal_preference_member_id'), ['member_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seasonal_preference', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seasonal_preference_member_id'))

    op.drop_table('seasonal_preference')
    # ### end Alembic commands ###
