"""add attach_image boolean to message queue table

Revision ID: c812a290660f
Revises: cb614c760fd5
Create Date: 2023-11-28 10:04:26.352473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c812a290660f'
down_revision = 'cb614c760fd5'
branch_labels = None
depends_on = None


def upgrade():
    # Add the column as nullable
    with op.batch_alter_table('message_queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attach_image', sa.Boolean(), nullable=True))

    # Set the default value for existing records
    op.execute(
        'UPDATE message_queue SET attach_image = false WHERE attach_image IS NULL'
    )

    # Alter column to non-nullable
    with op.batch_alter_table('message_queue', schema=None) as batch_op:
        batch_op.alter_column('attach_image', nullable=False)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_queue', schema=None) as batch_op:
        batch_op.drop_column('attach_image')
    # ### end Alembic commands ###

