"""add message log direction

Revision ID: e1dfaad0d7dc
Revises: f64385e29715
Create Date: 2023-11-26 09:47:51.122022

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'e1dfaad0d7dc'
down_revision = 'f64385e29715'
branch_labels = None
depends_on = None


def upgrade():
    message_log_direction_enum = postgresql.ENUM('inbound', 'outbound', name='message_log_direction', create_type=False)
    message_log_direction_enum.create(op.get_bind(), checkfirst=True)
    
    with op.batch_alter_table('message_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direction', message_log_direction_enum, nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('error_message', sa.Text(), nullable=True),)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_log', schema=None) as batch_op:
        batch_op.drop_column('direction')
        batch_op.drop_column('status')
        batch_op.drop_column('error_message')
    op.execute('DROP TYPE IF EXISTS message_log_direction')
    # ### end Alembic commands ###
