"""adding message_log table and adding times to user member table

Revision ID: f30b77816975
Revises: c6c2e01e7769
Create Date: 2023-11-25 16:18:15.427359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f30b77816975'
down_revision = 'c6c2e01e7769'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_ts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_modified', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_modified_ts', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_column('last_modified_ts')
        batch_op.drop_column('last_modified')
        batch_op.drop_column('created_ts')
        batch_op.drop_column('created')

    # ### end Alembic commands ###
