"""adding message queue table

Revision ID: f64385e29715
Revises: 991617a00a94
Create Date: 2023-11-25 23:01:54.992156

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'f64385e29715'
down_revision = '991617a00a94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('direction', postgresql.ENUM('inbound', 'outbound', name='message_direction'), nullable=False),
    sa.Column('from_number', sa.String(length=100), nullable=False),
    sa.Column('to_number', sa.String(length=100), nullable=False),
    sa.Column('message_body', sa.Text(), nullable=False),
    sa.Column('message_sid', sa.String(length=100), nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'SENDING', 'SENT', 'PROCESSING', 'PROCESSED', 'RECEIVED', 'HOLD', 'ERROR', name='messagequeuestatusenum'), nullable=False),
    sa.Column('hold', sa.Boolean(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('created_ts', sa.Integer(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('last_modified_ts', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_queue_member_id'), ['member_id'], unique=False)

    # with op.batch_alter_table('message_log', schema=None) as batch_op:
        # batch_op.drop_index('ix_message_log_sequence_id')
        # batch_op.drop_constraint('message_log_sequence_id_fkey', type_='foreignkey')
        # batch_op.drop_column('sequence_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('message_log', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('sequence_id', sa.INTEGER(), autoincrement=False, nullable=True))
        # batch_op.create_foreign_key('message_log_sequence_id_fkey', 'sequence', ['sequence_id'], ['id'])
        # batch_op.create_index('ix_message_log_sequence_id', ['sequence_id'], unique=False)

    with op.batch_alter_table('message_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_queue_member_id'))

    op.drop_table('message_queue')
    # ### end Alembic commands ###
    # Drop the enum type after dropping the table
    op.execute('DROP TYPE IF EXISTS message_direction')
    op.execute('DROP TYPE IF EXISTS messagequeuestatusenum')
